#Уникальний айди, будет использоватся на сервере для отображения
agent.id=Spot_1_server_BD
#ip сервера
server.ip=192.168.0.131
#Порт на который будет отправлятся информация
server.port=11984
#Интеравл, как часто отправлятся, в милисекундах, оптимальное время 1-5(тестировался в этом диапазоне)
metrics.interval=2000